### ISSUE TITLE
`npm install nsh -g` fails

### ISSUE THREAD

**Issue by serapath** [piranna/nsh#3]
with
```bash
/home/serapath/.nvm/versions/node/v8.1.0/bin/nsh -> /home/serapath/.nvm/versions/node/v8.1.0/lib/node_modules/nsh/nsh.js

> waitpid@0.1.1 install /home/serapath/.nvm/versions/node/v8.1.0/lib/node_modules/nsh/node_modules/waitpid
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/serapath/.nvm/versions/node/v8.1.0/lib/node_modules/nsh/node_modules/waitpid/build'
  CXX(target) Release/obj.target/waitpid/src/waitpid.o
../src/waitpid.cc:11:36: error: ‘Arguments’ does not name a type
 static Handle<Value> Waitpid(const Arguments& args) {
                                    ^
In file included from ../src/waitpid.cc:1:0:
/home/serapath/.node-gyp/8.1.0/include/node/v8.h: In function ‘v8::Handle<v8::Value> Waitpid(const int&)’:
/home/serapath/.node-gyp/8.1.0/include/node/v8.h:846:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/waitpid.cc:12:15: error: within this context
   HandleScope scope;
               ^
../src/waitpid.cc:15:13: error: invalid types ‘const int[int]’ for array subscript
   if (args[0]->IsInt32()) {
             ^
../src/waitpid.cc:16:19: error: invalid types ‘const int[int]’ for array subscript
     child = args[0]->Int32Value();
                   ^
../src/waitpid.cc:22:40: error: no matching function for call to ‘v8::Object::New()’
     Local<Object> result = Object::New();
                                        ^
In file included from ../src/waitpid.cc:1:0:
/home/serapath/.node-gyp/8.1.0/include/node/v8.h:3315:24: note: candidate: static v8::Local<v8::Object> v8::Object::New(v8::Isolate*)
   static Local<Object> New(Isolate* isolate);
                        ^
/home/serapath/.node-gyp/8.1.0/include/node/v8.h:3315:24: note:   candidate expects 1 argument, 0 provided
../src/waitpid.cc:25:19: error: ‘New’ is not a member of ‘v8::String’
       result->Set(String::New("exitCode"), Integer::New(WEXITSTATUS(status)));
                   ^
../src/waitpid.cc:25:76: error: no matching function for call to ‘v8::Integer::New(int)’
       result->Set(String::New("exitCode"), Integer::New(WEXITSTATUS(status)));
                                                                            ^
In file included from ../src/waitpid.cc:1:0:
/home/serapath/.node-gyp/8.1.0/include/node/v8.h:2764:25: note: candidate: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/serapath/.node-gyp/8.1.0/include/node/v8.h:2764:25: note:   candidate expects 2 arguments, 1 provided
../src/waitpid.cc:26:19: error: ‘New’ is not a member of ‘v8::String’
       result->Set(String::New("signalCode"), Null());
                   ^
../src/waitpid.cc:26:51: error: too few arguments to function ‘v8::Local<v8::Primitive> v8::Null(v8::Isolate*)’
       result->Set(String::New("signalCode"), Null());
                                                   ^
In file included from ../src/waitpid.cc:1:0:
/home/serapath/.node-gyp/8.1.0/include/node/v8.h:296:27: note: declared here
   friend Local<Primitive> Null(Isolate* isolate);
                           ^
../src/waitpid.cc:27:20: error: ‘class v8::HandleScope’ has no member named ‘Close’
       return scope.Close(result);
                    ^
../src/waitpid.cc:30:19: error: ‘New’ is not a member of ‘v8::String’
       result->Set(String::New("exitCode"), Null());
                   ^
../src/waitpid.cc:30:49: error: too few arguments to function ‘v8::Local<v8::Primitive> v8::Null(v8::Isolate*)’
       result->Set(String::New("exitCode"), Null());
                                                 ^
In file included from ../src/waitpid.cc:1:0:
/home/serapath/.node-gyp/8.1.0/include/node/v8.h:296:27: note: declared here
   friend Local<Primitive> Null(Isolate* isolate);
                           ^
../src/waitpid.cc:31:19: error: ‘New’ is not a member of ‘v8::String’
       result->Set(String::New("signalCode"), Integer::New(WTERMSIG(status)));
                   ^
../src/waitpid.cc:31:75: error: no matching function for call to ‘v8::Integer::New(int)’
       result->Set(String::New("signalCode"), Integer::New(WTERMSIG(status)));
                                                                           ^
In file included from ../src/waitpid.cc:1:0:
/home/serapath/.node-gyp/8.1.0/include/node/v8.h:2764:25: note: candidate: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/serapath/.node-gyp/8.1.0/include/node/v8.h:2764:25: note:   candidate expects 2 arguments, 1 provided
../src/waitpid.cc:32:20: error: ‘class v8::HandleScope’ has no member named ‘Close’
       return scope.Close(result);
                    ^
../src/waitpid.cc:34:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(Undefined());
                  ^
../src/waitpid.cc:34:34: error: too few arguments to function ‘v8::Local<v8::Primitive> v8::Undefined(v8::Isolate*)’
     return scope.Close(Undefined());
                                  ^
In file included from ../src/waitpid.cc:1:0:
/home/serapath/.node-gyp/8.1.0/include/node/v8.h:295:27: note: declared here
   friend Local<Primitive> Undefined(Isolate* isolate);
                           ^
../src/waitpid.cc:37:44: error: ‘New’ is not a member of ‘v8::String’
     return ThrowException(Exception::Error(String::New("Not an integer.")));
                                            ^
../src/waitpid.cc:37:75: error: ‘ThrowException’ was not declared in this scope
     return ThrowException(Exception::Error(String::New("Not an integer.")));
                                                                           ^
In file included from ../src/waitpid.cc:1:0:
/home/serapath/.node-gyp/8.1.0/include/node/v8.h: In function ‘void init(v8::Handle<v8::Object>)’:
/home/serapath/.node-gyp/8.1.0/include/node/v8.h:846:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/waitpid.cc:43:15: error: within this context
   HandleScope scope;
               ^
../src/waitpid.cc:44:45: error: invalid conversion from ‘v8::Handle<v8::Value> (*)(const int&) {aka v8::Local<v8::Value> (*)(const int&)}’ to ‘v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}’ [-fpermissive]
   NODE_SET_METHOD(target, "waitpid", Waitpid);
                                             ^
In file included from ../src/waitpid.cc:2:0:
/home/serapath/.node-gyp/8.1.0/include/node/node.h:270:13: note:   initializing argument 3 of ‘void node::NODE_SET_METHOD(v8::Local<v8::Object>, const char*, v8::FunctionCallback)’
 inline void NODE_SET_METHOD(v8::Local<v8::Object> recv,
             ^
waitpid.target.mk:93: recipe for target 'Release/obj.target/waitpid/src/waitpid.o' failed
make: *** [Release/obj.target/waitpid/src/waitpid.o] Error 1
make: Leaving directory '/home/serapath/.nvm/versions/node/v8.1.0/lib/node_modules/nsh/node_modules/waitpid/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/serapath/.nvm/versions/node/v8.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Linux 4.8.0-54-generic
gyp ERR! command "/home/serapath/.nvm/versions/node/v8.1.0/bin/node" "/home/serapath/.nvm/versions/node/v8.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/serapath/.nvm/versions/node/v8.1.0/lib/node_modules/nsh/node_modules/waitpid
gyp ERR! node -v v8.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! waitpid@0.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the waitpid@0.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/serapath/.npm/_logs/2017-06-16T00_20_44_606Z-debug.log
```

npm version 5.0.3
node version 8.1.0

**Comment by piranna** [comment]
This is a problem of waitpid module, not nsh.
